swagger: "2.0"
info:
  title: Note Taking API Docs
  description: A documentation of Note taking app built in Express.Js and MongoDB with user authentication
  version: 1.0
  contact:
    email: mhassancs260@gmail.com

schemes:
  - http

paths:
  /note/add-note:
    post:
      summary: Add a note 
      description: Endpoint to add note.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: Token for user Authorization
          required: true
          type: string

        - in: body
          name: add note
          description: The note to be added
          required: true
          schema:
            type: object
            properties:
              title:
                type: string
              content:
                type: string
      responses:
        201:
          description: Note added successfully.
          schema:
            type: object
            properties:
              flag:
                type: boolean
              message:
                type: string
              
        500:
          description: Internal Server Error.
          schema:
            type: object
            properties:
              flag:
                type: boolean
              message:
                type: string

servers:
  - url: "http://localhost:3000"
    description: A local development server
